# Generated by Django 5.0.7 on 2024-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='date_finished',
            field=models.DateField(blank=True, default='???'),
        ),
    ]
