# Generated by Django 5.0.7 on 2024-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0002_alter_gamelist_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='date_finished',
            field=models.DateField(blank=True),
        ),
    ]
