# Generated by Django 5.0.7 on 2024-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0004_alter_gamelist_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='game_image',
            field=models.ImageField(blank=True, default='', upload_to='gameimages/'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game_name',
            field=models.CharField(max_length=150),
        ),
    ]
