# Generated by Django 5.0.7 on 2024-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0005_gamelist_game_image_alter_gamelist_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_image',
            field=models.ImageField(blank=True, upload_to='gameimages/'),
        ),
    ]
