# Generated by Django 5.0.7 on 2024-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0006_alter_gamelist_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='other',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
