# Generated by Django 5.0.7 on 2024-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0010_alter_gamelist_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='gameimages/'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game_name',
            field=models.CharField(max_length=250),
        ),
    ]
