# Generated by Django 5.1.2 on 2024-10-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0013_rename_game_image_gamelist_game_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='game_image2',
            new_name='game_image',
        ),
    ]
